apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: authorino-server-metrics
  namespace: kuadrant-system
  labels:
    app.kubernetes.io/part-of: maas-observability
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      authorino-resource: authorino
  endpoints:
  - port: http
    path: /server-metrics
    interval: 30s
    scrapeTimeout: 10s
