apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: maas-tier-rate-limits
  namespace: openshift-ingress
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: maas-default-gateway
  defaults:
    strategy: merge
    limits:
      free-tier:
        rates:
        - limit: 5
          window: 1m
        when:
        - predicate: auth.identity.tier == "free"
        counters:
          - expression: auth.identity.userid
      premium-tier:
        rates:
        - limit: 60
          window: 1m
        when:
        - predicate: auth.identity.tier == "premium"
        counters:
          - expression: auth.identity.userid
      enterprise-tier:
        rates:
        - limit: 600
          window: 1m
        when:
        - predicate: auth.identity.tier == "enterprise"
        counters:
          - expression: auth.identity.userid
