apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: tier-free-rate-limits
  namespace: openshift-ingress
  labels:
    opendatahub.io/dashboard: "true"
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: maas-default-gateway
  defaults:
    strategy: merge
    limits:
      free-requests:
        rates:
        - limit: 5
          window: 1m0s
        when:
        - predicate: auth.identity.tier == "free" && !request.path.endsWith("/v1/models")
        counters:
        - expression: auth.identity.userid
---
apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: tier-premium-rate-limits
  namespace: openshift-ingress
  labels:
    opendatahub.io/dashboard: "true"
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: maas-default-gateway
  defaults:
    strategy: merge
    limits:
      premium-requests:
        rates:
        - limit: 60
          window: 1m0s
        when:
        - predicate: auth.identity.tier == "premium" && !request.path.endsWith("/v1/models")
        counters:
        - expression: auth.identity.userid
---
apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: tier-enterprise-rate-limits
  namespace: openshift-ingress
  labels:
    opendatahub.io/dashboard: "true"
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: maas-default-gateway
  defaults:
    strategy: merge
    limits:
      enterprise-requests:
        rates:
        - limit: 600
          window: 1m0s
        when:
        - predicate: auth.identity.tier == "enterprise" && !request.path.endsWith("/v1/models")
        counters:
        - expression: auth.identity.userid
